default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

mqtt:
  broker: localhost

influxdb:
  api_version: 2
  ssl: false
  host: !env_var INFLUXDB_HOST
  port: !env_var INFLUXDB_PORT
  token: !env_var INFLUXDB_TOKEN
  organization: !env_var INFLUXDB_ORG
  bucket: !env_var INFLUXDB_BUCKET_STATE

